// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yavozmbmlmhhypilespm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlhdm96bWJtbG1oaHlwaWxlc3BtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyOTM0NDgsImV4cCI6MjA1OTg2OTQ0OH0._hUJ1zxNnhVHXHGkHAQLOPs15LiXkTnqs4ZOLZNUiJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);